root: true
env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: 12
  sourceType: module
  parser: '@typescript-eslint/parser'
  project: './tsconfig.json'
  extraFileExtensions:
   - '.vue'
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/interface-name-prefix': 'off'
