env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 4
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/unbound-method': 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-misused-promises': 'off'
  '@typescript-eslint/interface-name-prefix': 'off'